# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.0 LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"

before_deploy:
      - git config --local user.name "Travis CI"
      - git config --local user.email "matiasevara@gmail.com"
      - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
      - git tag $GIT_TAG -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: 
    - ./examples/ToroHello.img
    - ./examples/ToroHello.img.sha256
    - ./examples/ToroException.img
    - ./examples/ToroException.img.sha256
    - ./examples/TorowithFileSystem.img
    - ./examples/TorowithFileSystem.img.sha256
    - ./examples/ToroPing.img
    - ./examples/ToroPing.img.sha256
    - ./examples/ToroFiles.img
    - ./examples/ToroFiles.img.sha256
  on:
     branch: master
  skip_cleanup: true

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./examples/travis.install.py

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./examples/travis.install.py
  - /bin/bash -c "sudo apt-get install qemu-system-x86"

script:
  # Build all test projects
  - lazbuild $LAZ_OPT ./examples/*.lpi
  - sha256sum ./examples/ToroHello.img > ./examples/ToroHello.img.sha256
  - sha256sum ./examples/ToroException.img > ./examples/ToroException.img.sha256
  - sha256sum ./examples/TorowithFileSystem.img > ./examples/TorowithFileSystem.img.sha256
  - sha256sum ./examples/ToroFiles.img > ./examples/ToroFiles.img.sha256
  - sha256sum ./examples/ToroPing.img > ./examples/ToroPing.img.sha256
  
notifications:
  email:
    on_success: false
    on_failure: false
