language: generic
sudo: required
dist: trusty
os:
- linux
env:
  global: 
before_install:
- openssl aes-256-cbc -K $encrypted_cfe8bf92ff86_key -iv $encrypted_cfe8bf92ff86_iv
  -in tests_rsa.enc -out /tmp/tests_rsa -d
- chmod +x ./ci/prepare_tests.sh
- chmod +x ./ci/run_tests.sh
- chmod +x ./ci/after_run.sh
- "./ci/prepare_tests.sh"
install:
- "./ci/run_tests.sh"
after_success:
- "./ci/after_run.sh"
after_failure:
- "./ci/after_run.sh"
notifications:
  email:
    on_success: false
    on_failure: true
