# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=1.8.2 LAZ_ENV=linux LAZ_OPT="--os=linux --cpu=x86_64"

before_deploy:
      - git config --local user.name "Travis CI"
      - git config --local user.email "matiasevara@gmail.com"
      - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
      - git tag $GIT_TAG -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: 
    - ./examples/HelloWorld/HelloWorld.img
    - ./examples/HelloWorld/HelloWorld.img.sha256
    - ./examples/ExceptionHandling/ExceptionHandling.img
    - ./examples/ExceptionHandling/ExceptionHandling.img.sha256
    - ./examples/StaticWebServer/StaticWebServer.img
    - ./examples/StaticWebServer/StaticWebServer.img.sha256
    - ./examples/WebSocketServer/WebSocketsServer.img
    - ./examples/WebSocketServer/WebSocketsServer.img.sha256
  on:
     branch: master
  skip_cleanup: true

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - chmod +x ./ci/travis.install.py
  - chmod +x ./ci/travis.compile.py

install:
  - ./ci/travis.install.py

script:
  - ./ci/travis.compile.py
 
notifications:
  email:
    on_success: false
    on_failure: false
