name: Repo-Sync

on: 
  schedule:
    - cron: '30 2 * * *'

jobs:
  repo-sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "torokernel/torokernel"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
